name: Dependency Checks

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request_target:

## NOTE: !!!
## When changing these workflows, ensure that the following is updated:
##   - Documentation: docs/continuous-integration.md
##   - Documentation: docs/makefile-cheat-sheet.md
##   - Makefile: ./GNUmakefile

jobs:
  checks:
    name: go mod
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: .go-version

      - name: Run make deps-check
        run: |
          echo "Using make to check dependencies"
          make deps-check
